# self.rowconfigure(0, minsize=60, weight=1)
# self.rowconfigure(1, minsize=60, weight=1)
# self.rowconfigure(2, minsize=60, weight=1)
# self.rowconfigure(3, minsize=30, weight=0)
# self.rowconfigure(4, minsize=30, weight=0)
# self.rowconfigure(5, minsize=60, weight=1)
# self.rowconfigure(6, minsize=30, weight=0)
# self.rowconfigure(7, minsize=30, weight=0)
# self.rowconfigure(8, minsize=30, weight=1)
# self.rowconfigure(9, minsize=60, weight=1)
# self.rowconfigure(10, minsize=60, weight=1)
# self.columnconfigure(0, minsize=60, weight=1)
# self.columnconfigure(1, minsize=60, weight=1)
# self.columnconfigure(2, minsize=60, weight=1)
# self.columnconfigure(3, minsize=60, weight=1)
# self.columnconfigure(4, minsize=60, weight=1)
# self.columnconfigure(5, minsize=30, weight=1)
# self.columnconfigure(6, minsize=60, weight=1)
# self.columnconfigure(7, minsize=60, weight=1)
# self.columnconfigure(8, minsize=60, weight=1)
# self.columnconfigure(9, minsize=60, weight=1)
# self.columnconfigure(10, minsize=60, weight=1)
# commit
#      button2 = tk.Button(self, text="Filler Button")
#      button2.grid(row=0, column=2, sticky=N+E+S+W)
#      button3 = tk.Button(self, text="Filler Button")
#      button3.grid(row=0, column=3, sticky=N+E+S+W)
#      button4 = tk.Button(self, text="Filler Button")
#      button4.grid(row=0, column=4, sticky=N+E+S+W)
#      button5 = tk.Button(self, text="Filler Button")
#      button5.grid(row=0, column=5, sticky=N+E+S+W)
#      button6 = tk.Button(self, text="Filler Button")
#      button6.grid(row=0, column=6, sticky=N+E+S+W)
#      button7 = tk.Button(self, text="Filler Button")
#      button7.grid(row=0, column=7, sticky=N+E+S+W)
#      button8 = tk.Button(self, text="Filler Button")
#      button8.grid(row=0, column=8, sticky=N+E+S+W)
#      button9 = tk.Button(self, text="Filler Button")
#      button9.grid(row=0, column=9, sticky=N+E+S+W)
#      button10 = tk.Button(self, text="Filler Button")
#      button10.grid(row=0, column=10, sticky=N+E+S+W)
#      button11 = tk.Button(self, text="Filler Button")
#      button11.grid(row=1, column=0, sticky=N+E+S+W)
#      button13 = tk.Button(self, text="Filler Button")
#      button13.grid(row=2, column=0, sticky=N+E+S+W)
#      button14 = tk.Button(self, text="Filler Button")
#      button14.grid(row=3, column=0, sticky=N+E+S+W)
#      button15 = tk.Button(self, text="Filler Button")
#      button15.grid(row=4, column=0, sticky=N+E+S+W)
#      button16 = tk.Button(self, text="Filler Button")
#      button16.grid(row=5, column=0, sticky=N+E+S+W)
#      button17 = tk.Button(self, text="Filler Button")
#      button17.grid(row=6, column=0, sticky=N+E+S+W)
#      button18 = tk.Button(self, text="Filler Button")
#      button18.grid(row=7, column=0, sticky=N+E+S+W)
#      button19 = tk.Button(self, text="Filler Button")
#      button19.grid(row=8, column=0, sticky=N+E+S+W)
#      button20 = tk.Button(self, text="Filler Button")
#      button20.grid(row=9, column=0, sticky=N+E+S+W)
#      button21 = tk.Button(self, text="Filler Button")
#      button21.grid(row=10, column=0, sticky=N+E+S+W)#
